services:
  next:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    container_name: sceo_next_service
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - next_node_modules:/usr/src/app/node_modules
      - next_build:/usr/src/app/.next
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: npm run dev
    networks:
      - backend

  nest:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    container_name: sceo_nest_service
    working_dir: /usr/src/app
    ports:
      - "4500:4500"
      - "5555:5555"
    volumes:
      - ./backend:/usr/src/app
      - nest_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - LM_STUDIO_URL=http://host.docker.internal:1234/v1
    command: npm run start:dev
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - backend

  postgresql:
    image: postgres:17.5-alpine
    container_name: sceo_postgres_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  maildev:
    image: maildev/maildev
    container_name: sceo_maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend

volumes:
  next_node_modules:
  nest_node_modules:
  next_build:
  postgresql-data:

networks:
  backend:
